### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zhb1589980152** [ZehuanZhang/tb618#1]
20:39:56.750/E: TypeError: Cannot find function waitFor in object 
function (mode) {...}. (<tb618>#2)
	at script(<tb618>:2)
是咋回事啊

**Comment by ZehuanZhang** [comment]
你使用的autojs版本是多少？

**Comment by ZehuanZhang** [comment]
已在[#f2d63b1](https://github.com/ZehuanZhang/tb618/commit/f323013b910023b832591cd672ca0f9aa5352832)中修复该问题，若当前软件版本号过低，将不会使用auto.waitFor检测是否开启无障碍模式
