### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by mitalos** [ZehuanZhang/tb618#2]
首先声明我不会任何编程
当这个脚本运行浏览的时候，默认时间经常因淘宝的小霸王服务器延迟原因，导致一开始不计时，几秒后(俩号测试，几秒都有)才弹出计时窗口，实际需要时长超过15s，这个脚本就不能完成浏览了
我xjb调整了那个sleep打头，括号内的时长(应该是吧，纯属瞎试)，就减少了失败率
感觉大佬应该延长下时间，就能保证成功，而不用重复了

**Comment by ZehuanZhang** [comment]
已在 [#f2d63b1](https://github.com/ZehuanZhang/tb618/commit/f323013b910023b832591cd672ca0f9aa5352832)中对这个问题进行修复，若你的客户端或网络导致延时严重，可适当增加swipeWaiting参数以避免过早结束浏览任务

**Comment by ZehuanZhang** [comment]
已在最新的更新中自动检测是否完成浏览，可以不用额外设置参数，并且使用时间最短
