### ISSUE TITLE
有几个步骤无法进行

### ISSUE THREAD

**Issue by king-zxw** [ZehuanZhang/tb618#3]
浏览618精选榜单，去天猫农场收菜（这个大概不能完成），浏览天猫榜单频道，浏览618爆款合集

**Comment by ZehuanZhang** [comment]
浏览类型的应该可以完成（我这边没问题），可以尝试使用最新的脚本 ，如果手机延迟严重，可以适当增加swipeWaiting的数值

**Comment by king-zxw** [comment]
有一个任务叫每天来领钱，邀请五位好友立即提现，可以加个功能让使用你的脚本的人帮你助力一下，五次助力即可提现，我看到规则是说每天可以最多可以开100个红包，单场次红包内两两用户仅可助力一次，

**Comment by ZehuanZhang** [comment]
哈哈，这个脚本只是偷偷懒用的，并不是很有动力去玩这种助力，我相信用这个脚本的朋友应该也只是想解放一下自己的双手，因此应该不会加这个额外的助力操作~

**Comment by king-zxw** [comment]
哈哈我看到去年双十一的时候，有人写了自动刷喵币的脚本，加上了给自己战队助力的功能，简直妙啊，当然也并不排斥，毕竟是别人的劳动所得

**Comment by ZehuanZhang** [comment]
恩恩，明天再测试一下，如果除了农场以外都可以正常进行，我就把这个issue关了

**Comment by ZehuanZhang** [comment]
已在最新的更新中自动检测是否完成浏览，可以不用额外设置参数，并且使用时间最短
