### ISSUE TITLE
运行脚本后，自动跳转到无障碍设置界面

### ISSUE THREAD

**Issue by lyzMaster** [ZehuanZhang/tb618#5]
我autojs无障碍权限已开。并且昨天运行(eval方式)该脚本可以正常。我尝试重新开关autojs无障碍权限，运行脚本后还是会自动跳转设置界面。

**Comment by ZehuanZhang** [comment]
这不一定是脚本的问题，以前我的设备auto js也出现过类似问题，这可能是auto js软件的bug，通常重新启动auto js或重启系统就会恢复正常。
另外如果真的是脚本的waitFor触发的auto js的bug，现可在eval前加一个变量指示是否关闭无障碍检测，例如：

```
GlobalDisableWaitFor = true;
eval(http.get('https://gitee.com/mimr/tb618/raw/master/tb618.js').body.string())
```

**Comment by ZehuanZhang** [comment]
需要注意的是，GlobalDisableWaitFor只对本脚本有效，不会影响auto.js的任何判断，若启用后仍然会跳转回无障碍设置界面，说明是auto.js本身的问题，这时候需要尝试重新开关auto.js程序或重启系统。
