### ISSUE TITLE
进入618列车界面总是失败？

### ISSUE THREAD

**Issue by whale-man** [ZehuanZhang/tb618#6]
在搜索栏输入"618列车"搜索，就会进入到活动界面了。建议逻辑修改成这样

**Comment by ZehuanZhang** [comment]
我这边运行良好，如果这个问题不是个例，可以后面改成使用搜索方案，这个方案之前做过，但目前出差无法修改

**Comment by ZehuanZhang** [comment]
已在 e9171a0 中对该问题进行修复

**Comment by ZehuanZhang** [comment]
在 b91d3558 中完全改为使用搜索方法进入活动主页面
