### ISSUE TITLE
小米8首页活动按钮、搜索框定位异常

### ISSUE THREAD

**Issue by zhongwangninja** [ZehuanZhang/tb618#9]
我的机型是小米 8，MIUI11 开发版对应安卓 10，已 ROOT。

不知道是否是系统或特殊机型导致的问题，我在打开淘宝后进入首页时会无法进入 618 页面，日志如下：
```
06:04:13.061/D: 检测无障碍模式是否开启
06:04:16.075/D: 欢迎来到领喵币脚本
Github项目: tb618
设备宽: 1080
设备高: 2248
手机型号: MI 8
安卓版本: 10
06:04:19.339/D: 打开手机淘宝
06:04:28.991/D: 当前在主界面
06:04:31.996/D: 尝试进入618列车界面
06:04:44.772/D: 进入主互动界面失败！
```

跟代码感觉是在首页“寻找 618 活动按钮”或者“寻找搜索框，尝试搜索入口进入活动”两个环节失败了。手动测试确认，如果我进入淘宝后，手动点击搜索，进入搜索页，可以继续后边的进程。

代码中，这个首页的活动点击块和搜索框都是根据 depth 和 index 来查找的，这块不太懂。如果方便的话，能否透露下这两个属性在 AutoJs 怎么确认，我继续排查看看。

另外有个关于搜索块定位的想法，如 Readme 中提到，淘宝“界面经常变动”。。。depth 和 index 这种属性大概也是随着首页布局调整，所以才会导致诸如 2020/06/13 这种首页层次变化就得更新代码的情况。

或许在定位搜索框的时候，可以根据 text 和 desc 来定位。比如搜索框的搜索按钮，点击会进入搜索页，和点击搜索框效果一致，这个搜索按钮是有 desc="搜索" 可以来定位的。且搜索按钮的“搜索”字段在小版本更新中变化的可能性较小。

感觉进入搜索页的代码如果用这个来做，可能会更通用
```
var searchButton = desc("搜索").findOnce();
click(searchButton.bounds().centerX(), searchButton.bounds().centerY()); sleep(3000);
```

或者这样处理效果可能会更好，页面微调后比较好处理：
```
// x,y 表示找到对应 text&desc 点击时的偏移量
// way 查找 text&desc 的方式，默认 equals，要求字段完全符合
// key 就是关键字段
function clickByKey (x, y, way, key) {

    switch (way) {
        case "matches":
            if (textMatches(key).exists()) {
                var keyBounds = textMatches(key).findOnce().bounds();
                click(keyBounds.centerX() + x, keyBounds.centerY() + y);
            } else if (descMatches(key).exists()) {
                var keyBounds = descMatches(key).findOnce().bounds();
                click(keyBounds.centerX() + x, keyBounds.centerY() + y);
            }
            break;
        default:
            if (textEndsWith(key).exists()) {
                var keyBounds = textEndsWith(key).findOnce().bounds();
                click(keyBounds.centerX() + x, keyBounds.centerY() + y);
            } else if (descEndsWith(key).exists()) {
                var keyBounds = descEndsWith(key).findOnce().bounds();
                click(keyBounds.centerX() + x, keyBounds.centerY() + y);
            }
    }
};

clickByKey(0, 0, "equals", "搜索"); sleep(3000);
```

---

如果改动影响稳定性，还请忽略，打扰了。
很赞的代码，感谢作者。

**Comment by ZehuanZhang** [comment]
关于首页层次的变化在今晨已做了调整，另外修复了搜索进入的逻辑问题，你这个提议很好，但是某些场景下text或desc属性可能是空的，另一方面，部分操作场景只使用text或desc搜索对象，会有搜索失败的可能性。
你提出的方法后续会测试，但目前可能不会直接加入代码，另外请问你是直接下载使用，还是采用每次在线拉取的方式运行脚本？

**Comment by ZehuanZhang** [comment]
可以尝试使用
```
eval(http.get('https://gitee.com/mimr/tb618/raw/master/tb618.js').body.string())
```
运行最新的脚本，若仍然有问题出现，请在该issue反馈

**Comment by zhongwangninja** [comment]
1. eval(http.get('https://gitee.com/mimr/tb618/raw/master/tb618.js').body.string())
2. https://gitee.com/mimr/tb618/raw/master/tb618.js 下载源码到本地，AutoJs 执行两种方式都试过

日志表现一致
```
12:40:48.395/D: 检测无障碍模式是否开启
12:40:51.948/D: 欢迎来到领喵币脚本
Github项目: tb618
设备宽: 1080
设备高: 2248
手机型号: MI 8
安卓版本: 10
脚本版本: 20200613-R12
12:40:55.022/D: 打开手机淘宝
12:41:04.944/D: 尝试进入618列车界面
12:41:09.037/D: 进入主互动界面失败！
```

跟踪了下最新代码
```
function CheckAndGoActivity(true) {
    if (IsOnMainForm() || IsOnSearchingForm()) {
        ShowMessage("尝试进入618列车界面");
        // 暂时取消按钮进入操作页面
        if (!GoActivityBySearching()) {
            ShowMessage("进入主互动界面失败！");
```
进入首页后
1. `IsOnMainForm() || IsOnSearchingForm()` 我的手机在这里表现正常，识别为首页&不在搜索页
2. `GoActivityBySearching()`我的手机识别异常了，添加部分日志如下输出
```
function GoActivityBySearching() {
    var searchBox = className("android.widget.FrameLayout").clickable(true).depth(13).findOnce();
    console.log(searchBox.text()); //首页
    console.log("searchBox coord({0}, {1})".format(searchBox.bounds().centerX(), searchBox.bounds().centerY())); //(87, 265)
    if (searchBox) {
        console.log("searchBox click"); //正常输出
        searchBox.click();
        sleep(1000);
    }

    console.log("IsOnSearching: " + IsOnSearching()); //false
```

- searchBox 识别为页面上角的首页标签，text 和 centerX(), centerY() 对比布局范围分析确实如此
- 点击首页后，IsOnSearching 判断为 false，符合代码预期，确实没有进入搜索页
- 手动点击进入搜索页，`console.log(className("android.view.View").depth(8).desc("语音搜索").exists());` 返回 true，代码符合预期

附上 AutoJs 布局范围分析的截图

- 手机淘宝首页
![image](https://user-images.githubusercontent.com/1947059/84560551-d6856000-ad77-11ea-9856-05138036775d.png)

- 首页标签的布局范围分析
![image](https://user-images.githubusercontent.com/1947059/84560593-206e4600-ad78-11ea-9888-032e9c74e8f1.png)

- 搜索框搜索按钮的布局范围分析
![image](https://user-images.githubusercontent.com/1947059/84560596-2e23cb80-ad78-11ea-930e-d6b24d6dbd46.png)

请问这个 searchbox 定位的是哪个元素，我可以在我的手机上找找看。

目前来看，是我的手机手机层次变化比较奇葩。。。不具有普遍性，不是 bug。

**Comment by ZehuanZhang** [comment]
可能是auto js搜索元素的顺序，或是系统排布元素顺序的差异引起的这个问题，目前已在 cdaaec69 中抛弃了以前的定位方法，你可以尝试一下是否仍然存在问题

**Comment by zhongwangninja** [comment]
![image](https://user-images.githubusercontent.com/1947059/84573237-d74ae000-add1-11ea-9c36-71907255547f.png)

最新版可以进入活动页了，👍
